<div class="footer-social">
  <div class="social-media">
    <img src="https://via.placeholder.com/310x135.png/#44C0B7" alt="Curtir pagina">
    <div class="social">
      <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/bis2bis/fa-instagram.svg'))?>" alt="Instagram">
      <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/bis2bis/fa-facebook-square.svg'))?>" alt="Facebook">
    </div>
  </div>
</div>