<div class="first-banner">
  <div class="slider-content">
    <div class="img-banner first">
      <img src="https://via.placeholder.com/1920x500.png/#44C0B7" alt="image">
    </div>
    <div class="img-banner second">
      <img src="https://via.placeholder.com/1920x500.png/#44C0B7" alt="image">
    </div>
    <div class="img-banner third">
      <img src="https://via.placeholder.com/1920x500.png/#44C0B7" alt="image">
    </div>
    <div class="img-banner fourth">
      <img src="https://via.placeholder.com/1920x500.png/#44C0B7" alt="image">
    </div>
  </div>
</div>

<script type="text/x-magento-init">
  {
    ".slider-content": {
      "Magento_Theme/js/slick-slider": {}
    }
  }
</script>